#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

# your commands here
cd /projectnb/bf528/users/wheeler/project_4

module load miniconda
conda activate project_4

cd samples

salmon index -t gentrome.fa.gz -d decoys.txt -p 12 -i salmon_index --gencode

echo "Job finished: $(date +%F)"